# Generated by Django 6.0.3 on 2026-04-01 15:16

import django.db.models.deletion
from django.db import migrations, models


def backfill_default_location(apps, schema_editor):
    Location = apps.get_model("tracker", "Location")
    User = apps.get_model("tracker", "User")
    Product = apps.get_model("tracker", "Product")
    DailyList = apps.get_model("tracker", "DailyList")

    loc, _ = Location.objects.get_or_create(
        slug="default",
        defaults={"name": "Default"},
    )
    User.objects.filter(location__isnull=True).update(location_id=loc.pk, is_approved=True)
    Product.objects.filter(location__isnull=True).update(location_id=loc.pk)
    DailyList.objects.filter(location__isnull=True).update(location_id=loc.pk)

    # Ensure unique (location, name) before AddConstraint: rename duplicate product names.
    from collections import defaultdict

    by_name = defaultdict(list)
    for p in Product.objects.filter(location_id=loc.pk).order_by("pk"):
        by_name[p.name].append(p)
    for name, rows in by_name.items():
        if len(rows) <= 1:
            continue
        for idx, p in enumerate(rows[1:], start=2):
            p.name = f"{name} ({idx})"
            p.save(update_fields=["name"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="is_approved",
            field=models.BooleanField(
                default=False,
                help_text="If false, the user cannot sign in until approved by a master user.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=150),
        ),
        migrations.AddField(
            model_name="dailylist",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_lists",
                to="tracker.location",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="tracker.location",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="tracker.location",
            ),
        ),
        migrations.RunPython(backfill_default_location, noop_reverse),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(fields=("location", "name"), name="unique_product_name_per_location"),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(fields=("location", "username"), name="unique_username_per_location"),
        ),
        migrations.AlterField(
            model_name="product",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="tracker.location",
            ),
        ),
        migrations.AlterField(
            model_name="dailylist",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_lists",
                to="tracker.location",
            ),
        ),
    ]
