# Generated by GPT-5.2 on 2026-04-26

from django.db import migrations, models
import django.db.models.deletion
import tracker.models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0002_location_tenancy"),
    ]

    operations = [
        migrations.CreateModel(
            name="Training",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trainings_created",
                        to="tracker.user",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainings",
                        to="tracker.location",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainingStep",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveIntegerField(default=0)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image", models.ImageField(blank=True, upload_to=tracker.models._training_step_upload_to)),
                ("image_url", models.URLField(blank=True)),
                (
                    "training",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="tracker.training",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]

